export const GET_NOTES = 'GET_NOTES'
export const CREATE_NOTE = 'CREATE_NOTE'
export const UPDATE_NOTE = 'UPDATE_NOTE'
export const DELETE_NOTE = 'DELETE_NOTE'
export const SELECT_NOTE = 'SELECT_NOTE'
export const EDIT_NOTE = 'EDIT_NOTE'
export const UPDATE_LIST_ORDER = 'UPDATE_LIST_ORDER'